In [1]:
import pandas as pd
import numpy as np

###Tratando dados nulos

In [2]:
utf = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'

df = pd.read_csv(utf, sep=';')
df

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [3]:
df.isnull() #True -> dados nulos e False -> dados não nulos

        Tipo  Bairro  Quartos  Vagas  Suites   Area  Valor  Condominio   IPTU
0      False   False    False  False   False  False  False       False  False
1      False   False    False  False   False  False  False        True   True
2      False   False    False  False   False  False  False       False  False
3      False   False    False  False   False  False  False       False  False
4      False   False    False  False   False  False  False       False   True
...      ...     ...      ...    ...     ...    ...    ...         ...    ...
32955  False   False    False  False   False  False  False       False  False
32956  False   False    False  False   False  False  False       False  False
32957  False   False    False  False   False  False  False       False  False
32958  False   False    False  False   False  False  False       False   True
32959  False   False    False  False   False  False  False       False  False

[32960 rows x 9 columns]

In [4]:
df.isnull().sum() #Soma a quantidade de dados nulos existentes True = 1 e False = 0

Tipo              0
Bairro            0
Quartos           0
Vagas             0
Suites            0
Area              0
Valor            17
Condominio     4093
IPTU          10237
dtype: int64

In [5]:
df.fillna(0)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,0.0
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [6]:
df = df.fillna(0)

In [7]:
df.isnull().sum()

Tipo          0
Bairro        0
Quartos       0
Vagas         0
Suites        0
Area          0
Valor         0
Condominio    0
IPTU          0
dtype: int64

Existem diversas formas de tratar dados nulos com o Pandas. Algumas das principais formas são:

    -> Remover os dados nulos: É possível remover as linhas ou colunas que possuem valores nulos utilizando o método dropna() . Esse método remove todas as linhas ou colunas que possuem pelo menos um valor nulo.

    -> Preencher os dados nulos: Utilizando o método fillna(), podemos preencher os valores nulos com um valor específico. Além disso, também é possível utilizar argumentos específicos do método fillna() como o method=”ffill” ou method=”bfill” para preencher os valores nulos com o valor anterior ou posterior, respectivamente.

    -> Interpolar os dados nulos: É possível utilizar o método interpolate() para preencher os valores nulos com valores interpolados, ou seja, valores calculados a partir dos valores vizinhos.

###Removendo registros

In [8]:
df.query('Valor == 0 | Condominio == 0' )

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,0.0,0.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0
10,Apartamento,Centro,1,0,0,36,1200.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
32914,Loja/Salão,Campo Grande,0,0,0,160,2650.0,0.0,0.0
32928,Loja/Salão,Leblon,0,0,0,68,25000.0,0.0,1113.0
32929,Loja/Salão,Freguesia (Jacarepaguá),0,0,0,80,5800.0,0.0,215.0
32931,Casa,Centro,5,0,1,160,5000.0,0.0,80.0
32954,Box/Garagem,Centro,0,0,0,755,14000.0,0.0,0.0

In [9]:
df.query('Valor == 0 | Condominio == 0').index

Index([    1,     5,     7,     8,    10,    16,    18,    31,    35,    76,
       ...
       32893, 32897, 32899, 32911, 32912, 32914, 32928, 32929, 32931, 32954],
      dtype='int64', length=4106)

In [10]:
registro_remover = df.query('Valor == 0 | Condominio == 0').index

In [11]:
df.drop(registro_remover, axis=0, inplace=True)

In [12]:
df.query('Valor == 0 | Condominio == 0')

Empty DataFrame
Columns: [Tipo, Bairro, Quartos, Vagas, Suites, Area, Valor, Condominio, IPTU]
Index: []

In [13]:
df.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0

In [14]:
df.drop('Tipo', axis = 1, inplace=True)

In [15]:
df.head()

            Bairro  Quartos  Vagas  Suites  Area   Valor  Condominio    IPTU
0       Copacabana        1      0       0    40  1700.0       500.0    60.0
2  Barra da Tijuca        0      4       0   150  5200.0      4020.0  1111.0
3           Centro        1      0       0    15   800.0       390.0    20.0
4     Higienópolis        1      0       0    48   800.0       230.0     0.0
6         Cachambi        2      0       0    50  1300.0       301.0    17.0

###Aplicando filtros